apiVersion: v1
kind: Namespace
metadata:
  name: test


---

apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - echo "Hello"; sleep 1000
    resources:
      limits:
        cpu: 200m
        memory: "1Gi"