apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx 
  labels:
    name: nginx-test
spec:
  replicas: 1 
  selector: 
    name: nginx-test
  template:
    metadata:
      labels:
        name: nginx-test

    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  labels:
    name: nginx-test
spec:
  type: NodePort
  selector:
     name: nginx-test
  ports:
    - port: 80 