apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: app-runtime
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-runtime
  template:
    metadata:
      labels:
        app: app-runtime
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.1
        ports:
        - containerPort: 80