apiVersion: v1
kind: Namespace
metadata:
  name: web

---


apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: web
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 9090
      name: redis
      protocol: TCP